package export

import (
	"fmt"
	"strings"
)

// NodeInput represents a node from the frontend
type NodeInput struct {
	ID       string                 `json:"id"`
	Type     string                 `json:"type"`
	Data     map[string]interface{} `json:"data"`
	Position map[string]float64     `json:"position"`
}

// EdgeInput represents an edge from the frontend
type EdgeInput struct {
	ID     string `json:"id"`
	Source string `json:"source"`
	Target string `json:"target"`
}

// TerraformGenerator generates Terraform HCL code
type TerraformGenerator struct {
	nodes []NodeInput
	edges []EdgeInput
}

// NewTerraformGenerator creates a new Terraform generator
func NewTerraformGenerator(nodes []NodeInput, edges []EdgeInput) *TerraformGenerator {
	return &TerraformGenerator{
		nodes: nodes,
		edges: edges,
	}
}

// Generate generates the complete Terraform configuration
func (g *TerraformGenerator) Generate() string {
	var output strings.Builder

	// Header
	output.WriteString("# Generated by Architecture Visualization Platform\n")
	output.WriteString("# Date: " + fmt.Sprintf("%v", "now") + "\n\n")

	// Provider configuration
	output.WriteString(g.generateProvider())
	output.WriteString("\n")

	// Variables
	output.WriteString(g.generateVariables())
	output.WriteString("\n")

	// Resources
	for _, node := range g.nodes {
		resource := g.nodeToTerraformResource(node)
		if resource != "" {
			output.WriteString(resource)
			output.WriteString("\n")
		}
	}

	// Outputs
	output.WriteString(g.generateOutputs())

	return output.String()
}

// generateProvider generates provider configuration
func (g *TerraformGenerator) generateProvider() string {
	return `terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
`
}

// generateVariables generates variable definitions
func (g *TerraformGenerator) generateVariables() string {
	return `variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "dev"
}

variable "project_name" {
  description = "Project name for resource naming"
  type        = string
  default     = "arch-viz"
}
`
}

// nodeToTerraformResource converts a node to Terraform resource
func (g *TerraformGenerator) nodeToTerraformResource(node NodeInput) string {
	config := node.Data["config"].(map[string]interface{})
	label := node.Data["label"].(string)
	resourceName := sanitizeName(label)

	switch node.Type {
	case "api_server", "web_server", "microservice", "worker":
		return g.generateEC2Instance(node.ID, resourceName, config)

	case "database_sql":
		return g.generateRDSInstance(node.ID, resourceName, config)

	case "database_nosql":
		return g.generateDynamoDB(node.ID, resourceName, config)

	case "cache_redis":
		return g.generateElastiCache(node.ID, resourceName, config)

	case "load_balancer":
		return g.generateALB(node.ID, resourceName, config)

	case "queue":
		return g.generateSQS(node.ID, resourceName, config)

	case "object_storage":
		return g.generateS3Bucket(node.ID, resourceName, config)

	case "lambda_function":
		return g.generateLambda(node.ID, resourceName, config)

	case "api_gateway":
		return g.generateAPIGateway(node.ID, resourceName, config)

	case "vpc", "subnet":
		return g.generateVPC(node.ID, resourceName, config)

	default:
		return fmt.Sprintf("# Unsupported node type: %s (%s)\n", node.Type, label)
	}
}

// Generate EC2 Instance
func (g *TerraformGenerator) generateEC2Instance(id, name string, config map[string]interface{}) string {
	instanceType := getStringOrDefault(config, "instanceType", "t3.micro")

	return fmt.Sprintf(`resource "aws_instance" "%s" {
  ami           = data.aws_ami.ubuntu.id
  instance_type = "%s"

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, instanceType, name)
}

// Generate RDS Instance
func (g *TerraformGenerator) generateRDSInstance(id, name string, config map[string]interface{}) string {
	engine := getStringOrDefault(config, "databaseEngine", "postgres")
	instanceType := getStringOrDefault(config, "instanceType", "db.t3.micro")
	storageGB := getIntOrDefault(config, "storage_size_gb", 20)

	return fmt.Sprintf(`resource "aws_db_instance" "%s" {
  identifier           = "${var.project_name}-%s"
  engine               = "%s"
  engine_version       = "15.3"
  instance_class       = "%s"
  allocated_storage    = %d
  storage_type         = "gp3"
  
  db_name  = "mydb"
  username = "admin"
  password = var.db_password  # Store in secrets manager
  
  skip_final_snapshot = true
  
  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name, engine, instanceType, storageGB, name)
}

// Generate DynamoDB Table
func (g *TerraformGenerator) generateDynamoDB(id, name string, config map[string]interface{}) string {
	return fmt.Sprintf(`resource "aws_dynamodb_table" "%s" {
  name           = "${var.project_name}-%s"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "id"

  attribute {
    name = "id"
    type = "S"
  }

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name, name)
}

// Generate ElastiCache (Redis)
func (g *TerraformGenerator) generateElastiCache(id, name string, config map[string]interface{}) string {
	nodeType := getStringOrDefault(config, "instanceType", "cache.t3.micro")

	return fmt.Sprintf(`resource "aws_elasticache_cluster" "%s" {
  cluster_id           = "${var.project_name}-%s"
  engine               = "redis"
  node_type            = "%s"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name, nodeType, name)
}

// Generate Application Load Balancer
func (g *TerraformGenerator) generateALB(id, name string, config map[string]interface{}) string {
	return fmt.Sprintf(`resource "aws_lb" "%s" {
  name               = "${var.project_name}-%s"
  internal           = false
  load_balancer_type = "application"
  subnets            = data.aws_subnets.default.ids

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name, name)
}

// Generate SQS Queue
func (g *TerraformGenerator) generateSQS(id, name string, config map[string]interface{}) string {
	return fmt.Sprintf(`resource "aws_sqs_queue" "%s" {
  name                      = "${var.project_name}-%s"
  delay_seconds             = 0
  max_message_size          = 262144
  message_retention_seconds = 345600
  receive_wait_time_seconds = 0

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name, name)
}

// Generate S3 Bucket
func (g *TerraformGenerator) generateS3Bucket(id, name string, config map[string]interface{}) string {
	return fmt.Sprintf(`resource "aws_s3_bucket" "%s" {
  bucket = "${var.project_name}-%s-${var.environment}"

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

resource "aws_s3_bucket_versioning" "%s_versioning" {
  bucket = aws_s3_bucket.%s.id

  versioning_configuration {
    status = "Enabled"
  }
}

`, name, name, name, name, name)
}

// Generate Lambda Function
func (g *TerraformGenerator) generateLambda(id, name string, config map[string]interface{}) string {
	runtime := getStringOrDefault(config, "runtime", "nodejs18.x")
	memoryMB := getIntOrDefault(config, "memoryMB", 128)

	return fmt.Sprintf(`resource "aws_lambda_function" "%s" {
  function_name = "${var.project_name}-%s"
  role          = aws_iam_role.%s_role.arn
  handler       = "index.handler"
  runtime       = "%s"
  memory_size   = %d
  timeout       = 30

  filename         = "lambda_function_payload.zip"
  source_code_hash = filebase64sha256("lambda_function_payload.zip")

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

resource "aws_iam_role" "%s_role" {
  name = "${var.project_name}-%s-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

`, name, name, name, runtime, memoryMB, name, name, name)
}

// Generate API Gateway
func (g *TerraformGenerator) generateAPIGateway(id, name string, config map[string]interface{}) string {
	return fmt.Sprintf(`resource "aws_api_gateway_rest_api" "%s" {
  name        = "${var.project_name}-%s"
  description = "API Gateway managed by Terraform"

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name, name)
}

// Generate VPC
func (g *TerraformGenerator) generateVPC(id, name string, config map[string]interface{}) string {
	return fmt.Sprintf(`resource "aws_vpc" "%s" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "${var.project_name}-%s"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

`, name, name)
}

// generateOutputs generates output values
func (g *TerraformGenerator) generateOutputs() string {
	var output strings.Builder

	output.WriteString("# Outputs\n")
	for _, node := range g.nodes {
		resourceName := sanitizeName(node.Data["label"].(string))
		switch node.Type {
		case "load_balancer":
			output.WriteString(fmt.Sprintf(`output "%s_dns" {
  value = aws_lb.%s.dns_name
}
`, resourceName, resourceName))
		case "api_gateway":
			output.WriteString(fmt.Sprintf(`output "%s_url" {
  value = aws_api_gateway_rest_api.%s.execution_arn
}
`, resourceName, resourceName))
		}
	}

	return output.String()
}

// Helper functions
func sanitizeName(name string) string {
	// Convert to lowercase and replace spaces with underscores
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, " ", "_")
	name = strings.ReplaceAll(name, "-", "_")
	return name
}

func getStringOrDefault(config map[string]interface{}, key, defaultValue string) string {
	if val, ok := config[key].(string); ok {
		return val
	}
	return defaultValue
}

func getIntOrDefault(config map[string]interface{}, key string, defaultValue int) int {
	if val, ok := config[key].(float64); ok {
		return int(val)
	}
	return defaultValue
}
